project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - Labs.qmd
      - Presentation.qmd
  
format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

